// Auto-generated TypeScript bindings for Rust native modules
// This file would normally be generated by napi-rs

export class NativeAsyncQueue {
  constructor(capacity?: number)
  push(item: any): boolean
  close(): void
  drain(): number
  len(): number
  is_empty(): boolean
  is_closed(): boolean
  capacity(): number
  next(): Promise<any>
  drain_all(): any[]
}

export class NativeRingBuffer {
  constructor(capacity?: number)
  push(chunk: string): boolean
  to_string(): string
  tail(maxBytes: number): string
  is_cut(): boolean
  len(): number
  is_empty(): boolean
  clear(): void
  capacity(): number
}

export class NativeLruCache {
  constructor(capacity?: number)
  get(key: string): any
  set(key: string, value: any): void
  has(key: string): boolean
  delete(key: string): boolean
  clear(): void
  len(): number
  is_empty(): boolean
  keys(): string[]
  values(): any[]
  capacity(): number
  prune(maxAgeSeconds: number): number
}
